### ISSUE TITLE
Numpy API compatibility issue in 2.7.1

### ISSUE THREAD

**Issue by jonas-eschle** [stevengj/nlopt#447]
With 2.7.1, there is an error when importing nlopt having a numpy version<1.22 installed.

Steps to reproduce:
install numpy<1.22, install nlopt

I think this is related to https://github.com/pypa/pip/issues/9542

Error message:
```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonas/anaconda3/envs/tmp38/lib/python3.8/site-packages/nlopt/__init__.py", line 1, in <module>
    from .nlopt import *
  File "/home/jonas/anaconda3/envs/tmp38/lib/python3.8/site-packages/nlopt/nlopt.py", line 20, in <module>
    from . import _nlopt
ImportError: numpy.core.multiarray failed to import
```

**Comment by jschueller** [comment]
you might want to report that to https://github.com/DanielBok/nlopt-python
